name: sheba_app
description: استعلام شماره شبا با شماره کارت
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  persian_number_utility: ^1.1.3
  zstandard: ^1.3.27
  archive: ^3.6.1
  # وابستگی‌های جدید برای کار با فایل اکسل
  file_picker: ^10.2.0
  excel: ^3.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  supabase_flutter: ^2.5.0 # Added Supabase dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700




